[project]
name = "ytdl-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiosqlite>=0.22.1",
    "celery>=5.6.0",
    "fastapi>=0.120.3",
    "pyyaml>=6.0.3",
    "uvicorn>=0.38.0",
    "yt-dlp>=2025.10.22",
]
